export type Country = {
    country: string;
    a2: string;
    a3: string;
    code: number;
};

export class ISO3166 {

    private countries: Country[] = [
        { country: "Afghanistan", a2: "AF", a3: "AFG", code: 4 },
        { country: "Albania", a2: "AL", a3: "ALB", code: 8 },
        { country: "Algeria", a2: "DZ", a3: "DZA", code: 12 },
        { country: "American Samoa", a2: "AS", a3: "ASM", code: 16 },
        { country: "Andorra", a2: "AD", a3: "AND", code: 20 },
        { country: "Angola", a2: "AO", a3: "AGO", code: 24 },
        { country: "Anguilla", a2: "AI", a3: "AIA", code: 660 },
        { country: "Antarctica", a2: "AQ", a3: "ATA", code: 10 },
        { country: "Antigua and Barbuda", a2: "AG", a3: "ATG", code: 28 },
        { country: "Argentina", a2: "AR", a3: "ARG", code: 32 },
        { country: "Armenia", a2: "AM", a3: "ARM", code: 51 },
        { country: "Aruba", a2: "AW", a3: "ABW", code: 533 },
        { country: "Australia", a2: "AU", a3: "AUS", code: 36 },
        { country: "Austria", a2: "AT", a3: "AUT", code: 40 },
        { country: "Azerbaijan", a2: "AZ", a3: "AZE", code: 31 },
        { country: "Bahamas (the)", a2: "BS", a3: "BHS", code: 44 },
        { country: "Bahrain", a2: "BH", a3: "BHR", code: 48 },
        { country: "Bangladesh", a2: "BD", a3: "BGD", code: 50 },
        { country: "Barbados", a2: "BB", a3: "BRB", code: 52 },
        { country: "Belarus", a2: "BY", a3: "BLR", code: 112 },
        { country: "Belgium", a2: "BE", a3: "BEL", code: 56 },
        { country: "Belize", a2: "BZ", a3: "BLZ", code: 84 },
        { country: "Benin", a2: "BJ", a3: "BEN", code: 204 },
        { country: "Bermuda", a2: "BM", a3: "BMU", code: 60 },
        { country: "Bhutan", a2: "BT", a3: "BTN", code: 64 },
        { country: "Bolivia (Plurinational State of)", a2: "BO", a3: "BOL", code: 68 },
        { country: "Bonaire, Sint Eustatius and Saba", a2: "BQ", a3: "BES", code: 535 },
        { country: "Bosnia and Herzegovina", a2: "BA", a3: "BIH", code: 70 },
        { country: "Botswana", a2: "BW", a3: "BWA", code: 72 },
        { country: "Bouvet Island", a2: "BV", a3: "BVT", code: 74 },
        { country: "Brazil", a2: "BR", a3: "BRA", code: 76 },
        { country: "British Indian Ocean Territory (the)", a2: "IO", a3: "IOT", code: 86 },
        { country: "Brunei Darussalam", a2: "BN", a3: "BRN", code: 96 },
        { country: "Bulgaria", a2: "BG", a3: "BGR", code: 100 },
        { country: "Burkina Faso", a2: "BF", a3: "BFA", code: 854 },
        { country: "Burundi", a2: "BI", a3: "BDI", code: 108 },
        { country: "Cabo Verde", a2: "CV", a3: "CPV", code: 132 },
        { country: "Cambodia", a2: "KH", a3: "KHM", code: 116 },
        { country: "Cameroon", a2: "CM", a3: "CMR", code: 120 },
        { country: "Canada", a2: "CA", a3: "CAN", code: 124 },
        { country: "Cayman Islands (the)", a2: "KY", a3: "CYM", code: 136 },
        { country: "Central African Republic (the)", a2: "CF", a3: "CAF", code: 140 },
        { country: "Chad", a2: "TD", a3: "TCD", code: 148 },
        { country: "Chile", a2: "CL", a3: "CHL", code: 152 },
        { country: "China", a2: "CN", a3: "CHN", code: 156 },
        { country: "Christmas Island", a2: "CX", a3: "CXR", code: 162 },
        { country: "Cocos (Keeling) Islands (the)", a2: "CC", a3: "CCK", code: 166 },
        { country: "Colombia", a2: "CO", a3: "COL", code: 170 },
        { country: "Comoros (the)", a2: "KM", a3: "COM", code: 174 },
        { country: "Congo (the Democratic Republic of the)", a2: "CD", a3: "COD", code: 180 },
        { country: "Congo (the)", a2: "CG", a3: "COG", code: 178 },
        { country: "Cook Islands (the)", a2: "CK", a3: "COK", code: 184 },
        { country: "Costa Rica", a2: "CR", a3: "CRI", code: 188 },
        { country: "Croatia", a2: "HR", a3: "HRV", code: 191 },
        { country: "Cuba", a2: "CU", a3: "CUB", code: 192 },
        { country: "Curaçao", a2: "CW", a3: "CUW", code: 531 },
        { country: "Cyprus", a2: "CY", a3: "CYP", code: 196 },
        { country: "Czechia", a2: "CZ", a3: "CZE", code: 203 },
        { country: "Côte d'Ivoire", a2: "CI", a3: "CIV", code: 384 },
        { country: "Denmark", a2: "DK", a3: "DNK", code: 208 },
        { country: "Djibouti", a2: "DJ", a3: "DJI", code: 262 },
        { country: "Dominica", a2: "DM", a3: "DMA", code: 212 },
        { country: "Dominican Republic (the)", a2: "DO", a3: "DOM", code: 214 },
        { country: "Ecuador", a2: "EC", a3: "ECU", code: 218 },
        { country: "Egypt", a2: "EG", a3: "EGY", code: 818 },
        { country: "El Salvador", a2: "SV", a3: "SLV", code: 222 },
        { country: "Equatorial Guinea", a2: "GQ", a3: "GNQ", code: 226 },
        { country: "Eritrea", a2: "ER", a3: "ERI", code: 232 },
        { country: "Estonia", a2: "EE", a3: "EST", code: 233 },
        { country: "Eswatini", a2: "SZ", a3: "SWZ", code: 748 },
        { country: "Ethiopia", a2: "ET", a3: "ETH", code: 231 },
        { country: "Falkland Islands (the) [Malvinas]", a2: "FK", a3: "FLK", code: 238 },
        { country: "Faroe Islands (the)", a2: "FO", a3: "FRO", code: 234 },
        { country: "Fiji", a2: "FJ", a3: "FJI", code: 242 },
        { country: "Finland", a2: "FI", a3: "FIN", code: 246 },
        { country: "France", a2: "FR", a3: "FRA", code: 250 },
        { country: "French Guiana", a2: "GF", a3: "GUF", code: 254 },
        { country: "French Polynesia", a2: "PF", a3: "PYF", code: 258 },
        { country: "French Southern Territories (the)", a2: "TF", a3: "ATF", code: 260 },
        { country: "Gabon", a2: "GA", a3: "GAB", code: 266 },
        { country: "Gambia (the)", a2: "GM", a3: "GMB", code: 270 },
        { country: "Georgia", a2: "GE", a3: "GEO", code: 268 },
        { country: "Germany", a2: "DE", a3: "DEU", code: 276 },
        { country: "Ghana", a2: "GH", a3: "GHA", code: 288 },
        { country: "Gibraltar", a2: "GI", a3: "GIB", code: 292 },
        { country: "Greece", a2: "GR", a3: "GRC", code: 300 },
        { country: "Greenland", a2: "GL", a3: "GRL", code: 304 },
        { country: "Grenada", a2: "GD", a3: "GRD", code: 308 },
        { country: "Guadeloupe", a2: "GP", a3: "GLP", code: 312 },
        { country: "Guam", a2: "GU", a3: "GUM", code: 316 },
        { country: "Guatemala", a2: "GT", a3: "GTM", code: 320 },
        { country: "Guernsey", a2: "GG", a3: "GGY", code: 831 },
        { country: "Guinea", a2: "GN", a3: "GIN", code: 324 },
        { country: "Guinea-Bissau", a2: "GW", a3: "GNB", code: 624 },
        { country: "Guyana", a2: "GY", a3: "GUY", code: 328 },
        { country: "Haiti", a2: "HT", a3: "HTI", code: 332 },
        { country: "Heard Island and McDonald Islands", a2: "HM", a3: "HMD", code: 334 },
        { country: "Holy See (the)", a2: "VA", a3: "VAT", code: 336 },
        { country: "Honduras", a2: "HN", a3: "HND", code: 340 },
        { country: "Hong Kong", a2: "HK", a3: "HKG", code: 344 },
        { country: "Hungary", a2: "HU", a3: "HUN", code: 348 },
        { country: "Iceland", a2: "IS", a3: "ISL", code: 352 },
        { country: "India", a2: "IN", a3: "IND", code: 356 },
        { country: "Indonesia", a2: "ID", a3: "IDN", code: 360 },
        { country: "Iran (Islamic Republic of)", a2: "IR", a3: "IRN", code: 364 },
        { country: "Iraq", a2: "IQ", a3: "IRQ", code: 368 },
        { country: "Ireland", a2: "IE", a3: "IRL", code: 372 },
        { country: "Isle of Man", a2: "IM", a3: "IMN", code: 833 },
        { country: "Israel", a2: "IL", a3: "ISR", code: 376 },
        { country: "Italy", a2: "IT", a3: "ITA", code: 380 },
        { country: "Jamaica", a2: "JM", a3: "JAM", code: 388 },
        { country: "Japan", a2: "JP", a3: "JPN", code: 392 },
        { country: "Jersey", a2: "JE", a3: "JEY", code: 832 },
        { country: "Jordan", a2: "JO", a3: "JOR", code: 400 },
        { country: "Kazakhstan", a2: "KZ", a3: "KAZ", code: 398 },
        { country: "Kenya", a2: "KE", a3: "KEN", code: 404 },
        { country: "Kiribati", a2: "KI", a3: "KIR", code: 296 },
        { country: "Korea (the Democratic People's Republic of", a2: "KP", a3: "PRK", code: 408 },
        { country: "Korea (the Republic of)", a2: "KR", a3: "KOR", code: 410 },
        { country: "Kuwait", a2: "KW", a3: "KWT", code: 414 },
        { country: "Kyrgyzstan", a2: "KG", a3: "KGZ", code: 417 },
        { country: "Lao People's Democratic Republic (the)", a2: "LA", a3: "LAO", code: 418 },
        { country: "Latvia", a2: "LV", a3: "LVA", code: 428 },
        { country: "Lebanon", a2: "LB", a3: "LBN", code: 422 },
        { country: "Lesotho", a2: "LS", a3: "LSO", code: 426 },
        { country: "Liberia", a2: "LR", a3: "LBR", code: 430 },
        { country: "Libya", a2: "LY", a3: "LBY", code: 434 },
        { country: "Liechtenstein", a2: "LI", a3: "LIE", code: 438 },
        { country: "Lithuania", a2: "LT", a3: "LTU", code: 440 },
        { country: "Luxembourg", a2: "LU", a3: "LUX", code: 442 },
        { country: "Macao", a2: "MO", a3: "MAC", code: 446 },
        { country: "Madagascar", a2: "MG", a3: "MDG", code: 450 },
        { country: "Malawi", a2: "MW", a3: "MWI", code: 454 },
        { country: "Malaysia", a2: "MY", a3: "MYS", code: 458 },
        { country: "Maldives", a2: "MV", a3: "MDV", code: 462 },
        { country: "Mali", a2: "ML", a3: "MLI", code: 466 },
        { country: "Malta", a2: "MT", a3: "MLT", code: 470 },
        { country: "Marshall Islands (the)", a2: "MH", a3: "MHL", code: 584 },
        { country: "Martinique", a2: "MQ", a3: "MTQ", code: 474 },
        { country: "Mauritania", a2: "MR", a3: "MRT", code: 478 },
        { country: "Mauritius", a2: "MU", a3: "MUS", code: 480 },
        { country: "Mayotte", a2: "YT", a3: "MYT", code: 175 },
        { country: "Mexico", a2: "MX", a3: "MEX", code: 484 },
        { country: "Micronesia (Federated States of)", a2: "FM", a3: "FSM", code: 583 },
        { country: "Moldova (the Republic of)", a2: "MD", a3: "MDA", code: 498 },
        { country: "Monaco", a2: "MC", a3: "MCO", code: 492 },
        { country: "Mongolia", a2: "MN", a3: "MNG", code: 496 },
        { country: "Montenegro", a2: "ME", a3: "MNE", code: 499 },
        { country: "Montserrat", a2: "MS", a3: "MSR", code: 500 },
        { country: "Morocco", a2: "MA", a3: "MAR", code: 504 },
        { country: "Mozambique", a2: "MZ", a3: "MOZ", code: 508 },
        { country: "Myanmar", a2: "MM", a3: "MMR", code: 104 },
        { country: "Namibia", a2: "NA", a3: "NAM", code: 516 },
        { country: "Nauru", a2: "NR", a3: "NRU", code: 520 },
        { country: "Nepal", a2: "NP", a3: "NPL", code: 524 },
        { country: "Netherlands (Kingdom of the)", a2: "NL", a3: "NLD", code: 528 },
        { country: "New Caledonia", a2: "NC", a3: "NCL", code: 540 },
        { country: "New Zealand", a2: "NZ", a3: "NZL", code: 554 },
        { country: "Nicaragua", a2: "NI", a3: "NIC", code: 558 },
        { country: "Niger (the)", a2: "NE", a3: "NER", code: 562 },
        { country: "Nigeria", a2: "NG", a3: "NGA", code: 566 },
        { country: "Niue", a2: "NU", a3: "NIU", code: 570 },
        { country: "Norfolk Island", a2: "NF", a3: "NFK", code: 574 },
        { country: "North Macedonia", a2: "MK", a3: "MKD", code: 807 },
        { country: "Northern Mariana Islands (the)", a2: "MP", a3: "MNP", code: 580 },
        { country: "Norway", a2: "NO", a3: "NOR", code: 578 },
        { country: "Oman", a2: "OM", a3: "OMN", code: 512 },
        { country: "Pakistan", a2: "PK", a3: "PAK", code: 586 },
        { country: "Palau", a2: "PW", a3: "PLW", code: 585 },
        { country: "Palestine, State of", a2: "PS", a3: "PSE", code: 275 },
        { country: "Panama", a2: "PA", a3: "PAN", code: 591 },
        { country: "Papua New Guinea", a2: "PG", a3: "PNG", code: 598 },
        { country: "Paraguay", a2: "PY", a3: "PRY", code: 600 },
        { country: "Peru", a2: "PE", a3: "PER", code: 604 },
        { country: "Philippines (the)", a2: "PH", a3: "PHL", code: 608 },
        { country: "Pitcairn", a2: "PN", a3: "PCN", code: 612 },
        { country: "Poland", a2: "PL", a3: "POL", code: 616 },
        { country: "Portugal", a2: "PT", a3: "PRT", code: 620 },
        { country: "Puerto Rico", a2: "PR", a3: "PRI", code: 630 },
        { country: "Qatar", a2: "QA", a3: "QAT", code: 634 },
        { country: "Romania", a2: "RO", a3: "ROU", code: 642 },
        { country: "Russian Federation (the)", a2: "RU", a3: "RUS", code: 643 },
        { country: "Rwanda", a2: "RW", a3: "RWA", code: 646 },
        { country: "Réunion", a2: "RE", a3: "REU", code: 638 },
        { country: "Saint Barthélemy", a2: "BL", a3: "BLM", code: 652 },
        { country: "Saint Helena, Ascension and Tristan da Cunha", a2: "SH", a3: "SHN", code: 654 },
        { country: "Saint Kitts and Nevis", a2: "KN", a3: "KNA", code: 659 },
        { country: "Saint Lucia", a2: "LC", a3: "LCA", code: 662 },
        { country: "Saint Martin (French part)", a2: "MF", a3: "MAF", code: 663 },
        { country: "Saint Pierre and Miquelon", a2: "PM", a3: "SPM", code: 666 },
        { country: "Saint Vincent and the Grenadines", a2: "VC", a3: "VCT", code: 670 },
        { country: "Samoa", a2: "WS", a3: "WSM", code: 882 },
        { country: "San Marino", a2: "SM", a3: "SMR", code: 674 },
        { country: "Sao Tome and Principe", a2: "ST", a3: "STP", code: 678 },
        { country: "Saudi Arabia", a2: "SA", a3: "SAU", code: 682 },
        { country: "Senegal", a2: "SN", a3: "SEN", code: 686 },
        { country: "Serbia", a2: "RS", a3: "SRB", code: 688 },
        { country: "Seychelles", a2: "SC", a3: "SYC", code: 690 },
        { country: "Sierra Leone", a2: "SL", a3: "SLE", code: 694 },
        { country: "Singapore", a2: "SG", a3: "SGP", code: 702 },
        { country: "Sint Maarten (Dutch part)", a2: "SX", a3: "SXM", code: 534 },
        { country: "Slovakia", a2: "SK", a3: "SVK", code: 703 },
        { country: "Slovenia", a2: "SI", a3: "SVN", code: 705 },
        { country: "Solomon Islands", a2: "SB", a3: "SLB", code: 90 },
        { country: "Somalia", a2: "SO", a3: "SOM", code: 706 },
        { country: "South Africa", a2: "ZA", a3: "ZAF", code: 710 },
        { country: "South Georgia and the South Sandwich Islands", a2: "GS", a3: "SGS", code: 239 },
        { country: "South Sudan", a2: "SS", a3: "SSD", code: 728 },
        { country: "Spain", a2: "ES", a3: "ESP", code: 724 },
        { country: "Sri Lanka", a2: "LK", a3: "LKA", code: 144 },
        { country: "Sudan (the)", a2: "SD", a3: "SDN", code: 729 },
        { country: "Suriname", a2: "SR", a3: "SUR", code: 740 },
        { country: "Svalbard and Jan Mayen", a2: "SJ", a3: "SJM", code: 744 },
        { country: "Sweden", a2: "SE", a3: "SWE", code: 752 },
        { country: "Switzerland", a2: "CH", a3: "CHE", code: 756 },
        { country: "Syrian Arab Republic (the)", a2: "SY", a3: "SYR", code: 760 },
        { country: "Taiwan (Province of China)", a2: "TW", a3: "TWN", code: 158 },
        { country: "Tajikistan", a2: "TJ", a3: "TJK", code: 762 },
        { country: "Tanzania, the United Republic of", a2: "TZ", a3: "TZA", code: 834 },
        { country: "Thailand", a2: "TH", a3: "THA", code: 764 },
        { country: "Timor-Leste", a2: "TL", a3: "TLS", code: 626 },
        { country: "Togo", a2: "TG", a3: "TGO", code: 768 },
        { country: "Tokelau", a2: "TK", a3: "TKL", code: 772 },
        { country: "Tonga", a2: "TO", a3: "TON", code: 776 },
        { country: "Trinidad and Tobago", a2: "TT", a3: "TTO", code: 780 },
        { country: "Tunisia", a2: "TN", a3: "TUN", code: 788 },
        { country: "Turkmenistan", a2: "TM", a3: "TKM", code: 795 },
        { country: "Turks and Caicos Islands (the)", a2: "TC", a3: "TCA", code: 796 },
        { country: "Tuvalu", a2: "TV", a3: "TUV", code: 798 },
        { country: "Türkiye", a2: "TR", a3: "TUR", code: 792 },
        { country: "Uganda", a2: "UG", a3: "UGA", code: 800 },
        { country: "Ukraine", a2: "UA", a3: "UKR", code: 804 },
        { country: "United Arab Emirates (the)", a2: "AE", a3: "ARE", code: 784 },
        { country: "United Kingdom of Great Britain  and Northern Ireland (the)", a2: "GB", a3: "GBR", code: 826 },
        { country: "United States Minor Outlying Islands the", a2: "UM", a3: "UMI", code: 581 },
        { country: "United States of America (the)", a2: "US", a3: "USA", code: 840 },
        { country: "Uruguay", a2: "UY", a3: "URY", code: 858 },
        { country: "Uzbekistan", a2: "UZ", a3: "UZB", code: 860 },
        { country: "Vanuatu", a2: "VU", a3: "VUT", code: 548 },
        { country: "Venezuela (Bolivarian Republic of)", a2: "VE", a3: "VEN", code: 862 },
        { country: "Viet Nam", a2: "VN", a3: "VNM", code: 704 },
        { country: "Virgin Islands (British)", a2: "VG", a3: "VGB", code: 92 },
        { country: "Virgin Islands (U.S.)", a2: "VI", a3: "VIR", code: 850 },
        { country: "Wallis and Futuna", a2: "WF", a3: "WLF", code: 876 },
        { country: "Western Sahara*", a2: "EH", a3: "ESH", code: 732 },
        { country: "Yemen", a2: "YE", a3: "YEM", code: 887 },
        { country: "Zambia", a2: "ZM", a3: "ZMB", code: 894 },
        { country: "Zimbabwe", a2: "ZW", a3: "ZWE", code: 716 },
         { country: "Åland Islandas", a2: "AX", a3: "ALA", code: 248 }
    ];

    public findCountryByAlpha2Code = (code: string): Country => {
        if (code.length != 2) {
            throw new Error("Invalid country code length. Must be 2");
        }
        return this.countries.find(country => country.a2 === code) || (() => { throw new Error("Invalid country code"); })();
    };

    public findCountryByAlpha3Code = (code: string): Country => {
        if (code.length != 3) {
            throw new Error("Invalid country code length. Must be 3");
        }
        return this.countries.find(country => country.a3 === code) || (() => { throw new Error("Invalid country code"); })();
    };

}
